peer:
    id: peer0.org1.example.com
    networkId: dev
    listenAddress: 0.0.0.0:7051
    address: 0.0.0.0:7051
    addressAutoDetect: false
    keepalive:
        minInterval: 60s
        client:
            interval: 60s
            timeout: 20s
        deliveryClient:
            interval: 60s
            timeout: 20s
    gossip:
        bootstrap: peer0.org1.example.com:7051
        useLeaderElection: true
        orgLeader: false
        membershipTrackerInterval: 5s
        endpoint:
        maxBlockCountToStore: 100
        maxPropagationBurstLatency: 10ms
        maxPropagationBurstSize: 10
        propagateIterations: 1
        propagatePeerNum: 3
        pullInterval: 4s
        pullPeerNum: 3
        requestStateInfoInterval: 4s
        publishStateInfoInterval: 4s
        stateInfoRetentionInterval:
        publishCertPeriod: 10s
        skipBlockVerification: false
        dialTimeout: 3s
        connTimeout: 2s
        recvBuffSize: 20
        sendBuffSize: 200
        digestWaitTime: 1s
        requestWaitTime: 1s
        responseWaitTime: 2s
        aliveTimeInterval: 5s
        aliveExpirationTimeout: 25s
        reconnectInterval: 25s
        maxConnectionAttempts: 120
        msgExpirationFactor: 20
        externalEndpoint:
    events:
        address: 0.0.0.0:7053
        buffersize: 100
        timeout: 10ms
        timewindow: 15m
        keepalive:
            minInterval: 60s
    tls:
        enabled: true
        clientAuthRequired: false
        cert:
            file: /etc/hyperledger/fabric/tls/server.crt
        key:
            file: /etc/hyperledger/fabric/tls/server.key
        rootcert:
            file: /etc/hyperledger/fabric/tls/ca.crt
        clientRootCAs:
            files:
              - /etc/hyperledger/fabric/tls/ca.crt
    authentication:
        timewindow: 15m
    chaincode:
        builder: $(DOCKER_NS)/fabric-ccenv:$(TWO_DIGIT_VERSION)
        pull: false
        golang:
            runtime: $(DOCKER_NS)/fabric-baseos:$(TWO_DIGIT_VERSION)
